# Generated by Django 3.2.16 on 2023-02-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0002_remove_voiture_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
